apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-state-metrics.fullname" . }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.http.name }}
      port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.name }}
      protocol: TCP
    - name: {{ .Values.service.telemetry.name }}
      port: {{ .Values.service.telemetry.port }}
      targetPort: {{ .Values.service.telemetry.name }}
      protocol: TCP
  selector:
    k8s-app: {{ include "kube-state-metrics.fullname" . }}